### ISSUE TITLE
Data ingestion: apply geometry dissolve to spark data frame rather than in geopandas

### ISSUE THREAD

**Issue by obi-defra** [Defra-Data-Science-Centre-of-Excellence/elmo-geo#125]
PR #122 introduced a dissolve step to the data pre-processing in the process_dataset.py notebook.

This dissolve process is currently only applied to datasets loaded with geopandas.

An improvement would be to apply a dissolve + explode to any input dataset.

There is a udf for applying a geopandas dissolve (elmo_geo.st.udf.st_union()) but a better method would be to use Sedonas ST_Union function. So as part of this task uses of st_union() should be replaced with the sedona function.

**Comment by sohauck** [comment]
Will be closed by #152
