### ISSUE TITLE
Riparian buffer strips define tasks and scope

### ISSUE THREAD

**Issue by sohauck** [Defra-Data-Science-Centre-of-Excellence/elmo-geo#160]

**Comment by aw-west-defra** [comment]
# Riparian Corridor Task
The objective is to create a score for the value of buffer strips using runoff concentration and parcel chemical load.
- Segmentise Boundaries
- Use ALERT (Crispin's flow model) to identify runoff per boundary
- Use fertiliser and pesticides loads scale chemical load per parcel

Shadow Crispin's team to explore
- their map, [link][1]
- creating ArcGIS tools.
- alternative ways of working

_This still needs expanding._

[1]: https://defra.maps.arcgis.com/apps/webappviewer/index.html?id=a611d861428741aea0d73a19160d885a

**Comment by aw-west-defra** [comment]
Ed's question, which parcels have risk of erosion.

**Comment by aw-west-defra** [comment]
Decided to produce
OLF Dataset for ELMO: `id_parcel, id_segment|None, fid_olf, score, <olf_scores>, olf_ha, catchment, subcatchment`
score calculation: `score = old_ha * mean(old_scores)`
